### PR TITLE
Frontend Updates

### PR DESCRIPTION
**Pull request by mrkno**
Includes:
- Conversion to ES6
- Removal of JQuery, beginnings of dust removal
- Access nodes via name rather than just ID
- Frontend properties control panel (disablable via `config.propertiesEditor`)
- Ability to select nodes
- Cross browser fixes
- Events
- Ability to add new edges via dragging (disabled in `graph.html`, toggle `config.propertiesEditor.addNew`)
 => done via new create API endpoint, `/vertices/createEdge`, passed `{"from":<id>,"to":<id>}`
- Ability to change what node edges connect to (disabled in `graph.html`, toggle `config.propertiesEditor.changeEdge`)
 => done via new update API endpoint, `/vertices/updateEdge`, passed `{"edgeId":<id>,"newDestNodeId":<id>}`
- Ability to delete nodes (disabled in `graph.html`, toggle `config.propertiesEditor.deleteSelection`)
 => done via new delete API endpoint, `/vertices/deleteVertex/<id>`

Does not include:
- Any server modifications required to enable features that require back-end endpoints
- Tests for changed or new functionality (manual tests have been performed)
- Updated gulp which supports ES6

### CODE REVIEW

**Comment by jenmud** [comment]
Well done @mrkno - Good work!

I can not wait to give it a go with [ruruki](https://github.com/optiver/ruruki). I same some work to do getting the createEdge and updateEdge working with the original backend.

Done forget to send me you Tshirt size :1st_place_medal:

**Comment by afmacedo** [comment]
Hi @mrkno, just had and opportunity to go through your changes.

First of all thanks for the huge effort upgrading the Eye to ES6 and (the most important aspect to me) getting rid of jQuery!!! Also contributing to make it a more easy-to-integrate and usable tool!

Code-wise everything seems to be in shape but I'm not inclined to merge it directly into **master** at this time because of the following points:

  * We are lacking a bit of documentation for public classes and methods
  * Tests (even though we have only a handful) are now broken
  * This is a very disruptive change and some of the tooling involved in the current assets processing is not yet ES6 compliant and prone to fail during building time (for the regular ``gulp dist`` case at least). Not a bad thing by all means, just one more thing to consider
  * Extra JS dependencies: one of our goals when creating the Eye was to make it as simple as possible to integrate and this includes not loading external external libs other than *ruruki-eye.js* and *d3*. Basically we should embed everything from ``app/js/*.js`` into ``ruruki-eye.js`` during the build phase (which is broken at the moment)

That said I propose you point your PR to ``es6-support`` instead of ``master`` for now.
Lets first stage and polish the change in a different branch without affecting possible existing users.
I offer to jump in and tweak the points mentioned above and as soon as we have ``es6-support`` in similar state of current ``master`` merge your changes.

**Comment by mrkno** [comment]
@afmacedo Sounds perfectly reasonable to me. I can't currently make this PR as github doesn't support PRing into new branches and I don't have permissions for this repo to create a new branch to PR into.

To add notes to your points:
* I agree there are a few "public" methods missing documentation, I am willing to go through and document these if it would be helpful - there are less "public" methods than it looks like at a glance, because the external dependencies that I have worked on are all contained within anonymous functions to prevent them being available outside their file.
* Tests are broken because of ES6 not being supported by uglify, in the past I have used babel to get around this problem and would be willing to look into this as well.
* It would be possible to merge these as part of `gulp dist` (and this was part of a future vision for them), currently they are separate to keep it modular - the ability to non-destructively inject code into ruruki-eye was the aim here. Merging these in may be harder than it looks at a glance because they are indirectly included via the HTML template files. I would propose that gulp deals with the templates as well (merges the templates into `graph.html`) which would remove that problem.

**Comment by afmacedo** [comment]
@mrkno I created the *es6-support* branch for you sarvo. Just replicate this PR there (as is) no change is necessary and I will merge it on the spot!

Great suggestion about merging the main/default templates during build time, I'll definitely try that! +1

Not everyone will consume Ruruki-Eye from graph.html so I like the idea of the user being able to extend the tool by pointing to their external templates too. Let's keep that around.

**Pull request closed without merging**
