### PR TITLE
Run as a packagge

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by jenmud** [comment]
I wonder is having an entry point is a better solution. The reason is because if you need to run the server on a different interface/ip address or run the server on a different port, it will not be possible.

Using a entry point, we can have a `run_server` which accepts command line arguments.

**Comment by techtonik** [comment]
I don't see why it is not possible.

**Comment by jenmud** [comment]
Declining with PR because using entry points seem to be a better solution.

**Comment by techtonik** [comment]
@jenmud do entrypoints work with standard Python and wheels? It always was a feature provided by external package. Entrypoints and running as a package are complementary features, not exclusive.

**Comment by jenmud** [comment]
@techtonik entry points are apart of setuptools, so when you do a pip install, it will create a entry point script pointing it to the function configured in your setup.py.

See [automatic-script-creation](https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation) for more detail.

**Comment by techtonik** [comment]
@jenmud you still need setuptools as a dependency, and you need to reinstall package every time after patching if you want to run and test it from source.

**Pull request closed without merging**
